name: Angular CI/CD

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'  # Use the Node.js version required for your Angular project

    - name: Install dependencies
      run: npm install

    - name: Build Angular app
      run: npm run build --prod

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'  # Use the Node.js version required for your Angular project

    - name: Install dependencies
      run: npm install

    - name: Build Angular app
      run: npm run build -- --prod

    - name: Deploy to GitHub Pages
      uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.4.0
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
      
